### PR TITLE
feature/#575 pandas 2.0 support

### PR DESCRIPTION
**Pull request by toan-quach**
#575 

BLOCKED: due to modin not yet officially release version 0.23, which also contains pandas 2.0.2

TODO:
- [x] Update based on changes in pandas 2.0.2
- [ ] update setup.py and pipfile to support new modin release (also contains new pandas version)

### CODE REVIEW

**Review by jrobinAV — DISMISSED** [review]

**Review by FabienLelaquais — DISMISSED** [review]
That looks neat!
What do you do with the Pipfile and the setup.py files?

**Comment by toan-quach** [comment]
@FabienLelaquais 
The plan is to wait for `modin` to release their newest version 0.23.0 (we hope it will be done by this week or at the latest, next week) and update our `Pipfile` and `setup.py` file then.
You can expect to see the changes in:
- `Pipfile` -> `modin = {extras = ["dask"], version = "==0.23.0"}`
- `setup.py` -> `"modin[dask]>=0.23.0,<1.0",`

**Comment by jrobinAV** [comment]
After changing the modin version to use 0.23.0rc0, a test fails to read an excel file.

I have created this bug report on modin project: https://github.com/modin-project/modin/issues/6338

**Review by jrobinAV — APPROVED** [review]
The merge must be synchronized with a pandas update merge on taipy-gui.

**Review by FabienLelaquais — APPROVED** [review]
👍

I guess the "update setup.py and pipfile" is done as well right?

**Pull request merged**
