### PR TITLE
add overloads for taipy.get()

### PR DESCRIPTION
**Pull request by Dr-Irv**
For use in applications, it is useful to know that if you pass a specific Id type, you get the corresponding type back.  So this PR adds overloads for `taipy.get()` to make it more friendlier when using typing checks.

Seems that black did some reformatting as well.

### CODE REVIEW

**Comment by Dr-Irv** [comment]
@jrobinAV  I was disappointed that this change didn't make it into the 2.1 release.

**Comment by jrobinAV** [comment]
Hi Irv,

**Comment by jrobinAV** [comment]
Hi Irv, 

Yes, We added some functionalities in the 2.1 version that required a lot of testing and documentation. We had no time to process this PR.
We do now. 
But don't worry, it is small enough to be included in a patch version 2.1.X that will come soon.
We let you know.

Thx again for the contribution.

**Review by jrobinAV — APPROVED** [review]
Neat.
Thank you,

**Pull request merged**
