### PR TITLE
run Config.check when core is running

### PR DESCRIPTION
**Pull request by jrobinAV**

### CODE REVIEW

**Review by trgiangdo — COMMENTED** [review]
Thank you. I should have done it but completely forgot.

Just a small suggestion before approve and merge this PR.
Since the parse_arguments method is slightly changed on when is called, can we test how it would affect the --help command when using with GUI agrparser?

**Comment by jrobinAV** [comment]
> 

Right, I am going to test that. 

For information, this PR is not blocking the release.

**Review by trgiangdo — DISMISSED** [review]
Thank you

**Review by toan-quach — DISMISSED** [review]
lgtm!

**Pull request merged**
